# Install and import Tidyverse.
install.packages('tidyverse')
library(tidyverse)
library(ggplot2)
library(corrplot)
library(olsrr)
library(reshape2)
library(lattice)

# Import the data
sales <- read.csv(file.choose(), header = TRUE)

# View Dataframe
glimpse(sales)


# Create a new data frame from a subset of the sales data frame.
# Remove unnecessary columns. 
sales2 <- subset (sales, select = -c(Ranking, Year, Genre, Publisher))


# View the data frame.
head(as_tibble (sales2))


# Descriptive statistics
summary(sales2)
##############################################################################

# Review plots to determine initial insights into data set.
# Create a scatterplot to visually determine relation between variables
qplot(NA_Sales, EU_Sales, data=sales2) 
qplot(NA_Sales, Global_Sales, data=sales2)
qplot(EU_Sales, Global_Sales, data=sales2)
# Scatterplots show there may be some linear correlation between the variables


# Create a correlation Matrix & visually check for Multicollinearity
# Create new DataFrame which only contains numerical values
sales3 <- subset(sales2, select = -c(Product, Platform))

# Create correlation matrix
corrplot(cor(sales3), method = 'number')
# Note some strong correlations across the board 
# Esp between NA_Sales & Global_Sales
# Makes sense given NA_Sales are likely a very large component of Global_Sales
# NA is a very large games market


# Continue testing for Multicollinearity with VIF values to statistically confirm
# This will confirm mathematically the visual confirmations
# Of correlation & Multicollinearity that has been detected 
# Using scatterplots & Correlation Matrix
# Create a fitted Multiple Regression Model
my_model <- lm(Global_Sales ~ EU_Sales + NA_Sales, data=sales3)
summary(my_model)

# Now Test for VIF & Tolerance
ols_vif_tol(my_model)
# VIF is below 3 = benchmark for accepting that there is no Multicollinearity

# Further test for multicollinearity using Eigenvalues & Condition Index
ols_eigen_cindex(my_model)
# Condition Index outputs are low
# Even though Variance is relatively high
# Given Condition Index Numbers are well below 10
# We can rule out Multicollinearity affirmatively.


# Create Histograms to visualize distribution of data
qplot(NA_Sales, bins=20, data=sales2)
qplot(EU_Sales, bins=20, data=sales2)
qplot(Global_Sales, bins=20, data=sales2)
# Both Regions and Global Sales show very strong right skew
# This implies that mean is greater than median sales 
# Which in turn implies that most of the sales are driven by a handful of products
# Out of the total products being offered


# Create boxplots to summarise the statistical characteristics of the distributions
# Reshaping the dataframe
data_long <- melt(sales3)
head(data_long)

# Create boxplots for all variables on a single chart
bwplot(value ~ variable, data_long)
# We can see lots of 'outliers' across the board
# Re-inforces the possibility discovered in the skewness of the distributions
# Most sales are generated by small selection of products.

#################################################################################

# Determine the impact on sales per product_id
df <- sales %>% group_by(Product) %>% summarise(across(.cols = c(NA_Sales, EU_Sales, Global_Sales), list(sum = sum)))

# Explore the DataFrame.
# Count the number of products
n <- nrow(df)
# Print
cat('Number of Unique Products :', n-1)
# 174 Unique products sold

# Calculate Total Sales per region
sum(df$NA_Sales_sum)
# GBP 885.62mio
sum(df$EU_Sales_sum)
# GBP 578.61mio
sum(df$Global_Sales_sum)
# GBP 1877.81mio
# Sum of Global_sales is higher than sums of NA_Sales & EU_Sales combined
# Indicates there are sales in other regions not present in the dataset

# Return top 25% products sold in each region and total value of such sales.
top_quart_NA <- head(sort(df$NA_Sales_sum,decreasing=TRUE),n=44)
top_quart_EU <- head(sort(df$EU_Sales_sum,decreasing=TRUE),n=44)
top_quart_Global <- head(sort(df$Global_Sales_sum,decreasing=TRUE),n=44)
# Calculate what their sales add up to
sum(top_quart_NA)
# 25% of total products sold (44 products) generate GBP 476.83mio in NA_Sales
# This is ~53% of total sales in NA

sum(top_quart_EU)
# 25% of total products sold (44 products) generate GBP 323.75mio in EU_Sales
# This is ~56% of total sales in EU

sum(top_quart_Global)
# 25% of total products sold (44 products) generate GBP 943.03mio in Global_Sales
# This is ~50% of total Global Sales.

# We can see that sales revenues are highly concentrated
# From a small number of products out of the total offered
# This confirms our finding previously taken from data distribution visualisation